package org.causwengteam13.issuetrackerserver.domain.project.service;

import org.causwengteam13.issuetrackerserver.domain.project.command.AnalyzeProjectByDateCommand;
import org.causwengteam13.issuetrackerserver.domain.project.command.AnalyzeProjectByMemberCommand;
import org.causwengteam13.issuetrackerserver.domain.project.result.AnalyzeProjectByDateResult;
import org.causwengteam13.issuetrackerserver.domain.project.result.AnalyzeProjectByMemberResult;

public interface AnalyzeProjectService {

	AnalyzeProjectByDateResult analyzeProjectByDate(AnalyzeProjectByDateCommand command);
	AnalyzeProjectByMemberResult analyzeProjectByMember(AnalyzeProjectByMemberCommand command);
}
